# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '${PORT}:${PORT}'
#     env_file:
#       - .env
#     volumes:
#       - .:/usr/src/app # Gắn kết thư mục hiện tại vào container để hỗ trợ hot-reload
#       - /usr/src/app/node_modules # Ngăn chặn việc ghi đè node_modules
#     depends_on:
#       - redis
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#       - REDIS_HOST=${REDIS_HOST}
#       - REDIS_PORT=${REDIS_PORT}
#       - SOCKET_IO_PORT=${SOCKET_IO_PORT}

#   redis:
#     image: redis:latest
#     ports:
#       - '${REDIS_PORT}:${REDIS_PORT}'
#     volumes:
#       - redis_data:/data

# volumes:
#   redis_data:
  





  

version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # Gắn kết thư mục hiện tại vào container để hỗ trợ hot-reload
      - /usr/src/app/node_modules # Ngăn chặn việc ghi đè node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL} # Sử dụng REDIS_URL từ .env
      - SOCKET_IO_PORT=${SOCKET_IO_PORT}
